### PR TITLE
Fix deprecation warning in Swift 4.0

### PR DESCRIPTION
**Pull request by jimmyti**
- Replace usage of *UIColor* constructor `init(colorLiteralRed:green:blue:alpha:)` with `init(red:green:blue:alpha:)`
- Fix spellings of `percent` and `percentage` for better code readability

### CODE REVIEW

**Comment by mpatzer** [comment]
I can verify these changes are correct. @juanpablofernandez Can you review and merge this PR?

**Comment by mpatzer** [comment]
@juanpablofernandez This PR needs to get merged for developers to continue using SwiftyOnboard.

**Comment by juanpablofernandez** [comment]
Sorry it took so long, it is now merged! 👍

**Comment by mpatzer** [comment]
Thanks!

**Pull request merged**
